# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48976fbe10d303995813e051b5b92f91f1cc2ca8460ecbf5534b7bb291cc565db78af62914011dff5b52b1e1980d83a5a2ebb8891419698213c7414b66c1e515

test:
  secret_key_base: 1286ba40756a9f0c4d0457eaa39eaa949009ab98112b887e39b2168d88e9aa6a065840e948ffac5b42751bc3b241414ec2034231a4ca90298cbdaa9e046463a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
